name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Install Netlify CLI
      run: npm install -g netlify-cli

    - name: Deploy to Netlify
      env:
        NETLIFY_AUTH_TOKEN: nfp_pdZBuA6UwyYFkp3WUfxLdbrevaQK3LhZba47
        NETLIFY_SITE_ID: c9eaf719-7b68-4937-9fc2-5d03bcec3155
      run: |
        netlify deploy --prod --dir=build --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN
